### PR TITLE
for v4.1

### PR DESCRIPTION
**Pull request by ltjin**

### CODE REVIEW

**Comment by pouledodue** [comment]
4.1.1?

**Comment by ltjin** [comment]
test 4.1.1, it's available

**Comment by pouledodue** [comment]
@ltjin (that code)[https://raw.githubusercontent.com/ltjin/charles-hacking/6be6de4efc039974747d6a1ee24fa795156972e6/hack.4.1.sh] does not work for me with 4.1.1

**Comment by pouledodue** [comment]
works thanks

**Comment by DrCharlesrandquist** [comment]
How to hack a Facebook with the phone number

**Pull request merged**
